---
title: Rlang and Quosures and !!! Oh My!
author: James Blair
date: '2017-06-28'
slug: tidyeval
categories: []
tags:
  - R
  - tidyverse
  - SoDS17
draft: true
description: "Adventures in tidyeval"
---

```{r setup, include=FALSE}
# knitr options
knitr::opts_chunk$set(message = FALSE)

# Packages
library(tidyverse)

# Set ggplot theme
theme_set(hrbrthemes::theme_ipsum())
```

I've noticed a lot of recent discussion around the latest version of [`dplyr`](http://dplyr.tidyverse.org/) and it's reliance on the [tidyeval](http://rlang.tidyverse.org/articles/tidy-evaluation.html) framework. In fact, twitter has been flooded with references to tidyeval.

<blockquote class="twitter-tweet" data-lang="en" align="center"><p lang="en" dir="ltr">Tis the season when many of us are coming to terms with <a href="https://twitter.com/hashtag/tidyeval?src=hash">#tidyeval</a> and feel the need to tell you about it. It&#39;s like CrossFit for <a href="https://twitter.com/hashtag/rstats?src=hash">#rstats</a>! 😉 <a href="https://t.co/CcmFteTc6l">https://t.co/CcmFteTc6l</a></p>&mdash; Jenny Bryan (@JennyBryan) <a href="https://twitter.com/JennyBryan/status/880114049475682305">June 28, 2017</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="en" align="center"><p lang="en" dir="ltr">😂😂😂 I broke R. <a href="https://t.co/AWx3Yq2Km2">pic.twitter.com/AWx3Yq2Km2</a></p>&mdash; Julia Silge (@juliasilge) <a href="https://twitter.com/juliasilge/status/880493031924809728">June 29, 2017</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="en" align="center"><p lang="en" dir="ltr">enquo() is dark magic</p>&mdash; Richie Cotton (@richierocks) <a href="https://twitter.com/richierocks/status/880550984518311937">June 29, 2017</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

I've been a `dplyr` fan in the past but I must admit I rely mainly on [`data.table`](https://github.com/Rdatatable/data.table/wiki) for my day to day data manipulation needs. However, the fact that `dplyr` interfaces so nicely with multiple backends (specifically [Spark](http://spark.rstudio.com/dplyr.html)) provides me with a compelling reason to keep up with it. That and the fact that my boss exclussively opperates in the [tidyverse](http://tidyverse.org). I also appreciate the syntactic sugar that comes free of charge with `dplyr`.

With the release of [`dplyr 0.7.0`](https://blog.rstudio.org/2017/06/13/dplyr-0-7-0/) (formerly `dplyr 0.6.0`) there was a major shift in the mechanics driving `dplyr's` Non Standard Evaluation (NSE). These updated mechanics are based solely on tidyeval principles based on functions contained in the [`rlang`](http://rlang.tidyverse.org/#overview) package. As explained in the tidy-evaluation vignette (`vignette("tidy-evaluation", package = "rlang")`) there are three features of the R language that make NSE possible:

1. R code is first-class
2. Scope is first-class
3. Functions can capture expressions that were supplied (as opposed to only capturing their evaluation)

In this post we'll examine each of these features with (hopefully) intuitive examples. My goal is to help develop some intuition around tidy evaluation and provide some guidelines to its usage. I'll extensively rely on both the previously described vignette along with Hadley Wickham's wonderful book [*Advanced R*](http://adv-r.hadley.nz/index.html).

## First class code

## First class scope

## 